
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

sources:
  - name: fy
    database: fy-project-291518
    schema: fy_raw
    tables:
      - name: dim_delighted_survey_responses
      - name: dim_delighted_users
      - name: dim_reviews
      - name: fct_order_statuses
      - name: fct_orders
